version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: escuela
      MYSQL_USER: docker
      MYSQL_PASSWORD: mititluloselollevoexpedition33
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=escuela
      - DB_USER=docker
      - DB_PASS=mititluloselollevoexpedition33
    depends_on:
      - db

volumes:
  db_data:
